Feat/#10 tabbar
OnAndOff-UMC/iOS pull request #11
Opened 2024-01-23 06:45 UTC by yeahzxnn

2024-01-24 04:23 UTC, HJ39 requested changes
왜 주석이 하나도 없나요..

2024-01-24 04:23 UTC, HJ39 commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +}
파일 분리 해주세요

2024-01-24 04:23 UTC, HJ39 commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +    fileprivate var selectedIndex = 0 {
왜 fileprivate 인가요?

2024-01-24 04:23 UTC, HJ39 commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +    fileprivate var tapSubject = PublishSubject<Int>()
이것도 왜 filepriavte인가요?

2024-01-24 04:23 UTC, HJ39 commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +    }
코드들 함수로 분리해 주세요

2024-01-24 04:23 UTC, HJ39 commented on On_off_iOS/On_off_iOS/TabBar/ViewController.swift
> +        tabBarController.modalPresentationStyle = .fullScreen
TabbarController를 왜 ViewController에서 호출하나요?

2024-01-24 04:34 UTC, HJ39 commented on On_off_iOS/On_off_iOS/TabBar/TabBarController.swift
> +}
어떤 기능의 코드인가요?

2024-01-24 04:37 UTC, HJ39 commented on On_off_iOS/On_off_iOS/TabBar/TabBarController.swift
> +        setUp()
ViewDidLoad가 아닌 Init에서 실행한 이유가 있나요?

2024-01-24 04:38 UTC, dami0806 commented on On_off_iOS/On_off_iOS/TabBar/TabBarController.swift
> +    fileprivate let tabBar = CustomTabBar()
왜 fileprivate으로 사용했나요?

2024-01-24 04:38 UTC, dami0806 commented on On_off_iOS/On_off_iOS/TabBar/TabBarController.swift
> +                guard let shouldFrontView = self.childVCs[index].view else { return }
self 제거해주세요

2024-01-24 04:38 UTC, dami0806 commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +        stackView.alignment = .center
stackView속성은  lazy var closure로 사용해주세요

2024-01-24 05:25 UTC, dami0806 commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +enum TabItem: Int, CaseIterable, Equatable {
Equatable는 없어도 될거 같아요!

2024-01-24 05:25 UTC, dami0806 commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +                .disposed(by: disposeBag)
tapSubject 동작로직 viewModel로 분리하면 좋슴다!!

2024-01-24 05:31 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +enum TabItem: Int, CaseIterable, Equatable {
넵!

2024-01-24 05:32 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +}
넵! Model - TabItem으로 분리하겠습니다.

2024-01-24 06:45 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +    fileprivate var selectedIndex = 0 {
불필요하다고 판단해 private으로 수정했습니다.

2024-01-24 06:48 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +    fileprivate var tapSubject = PublishSubject<Int>()
불필요하다고 판단해 제거했습니다.

2024-01-24 06:48 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/TabBar/ViewController.swift
> +        tabBarController.modalPresentationStyle = .fullScreen
ViewController을 제거하고 TabBarController에서 작동하도록 MVVM 다시 적용했습니다.

2024-01-26 12:48 UTC, HJ39 commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +                .disposed(by: disposeBag)
i를 명확한 변수로 변경해주세요

2024-01-26 16:00 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +    }
tabSubject, configureUI로 최대한 분리했습니다.

2024-01-26 16:01 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/TabBar/TabBarController.swift
> +}
이 코드는 ReactiveX 프레임워크의 Binder를 사용하여, CustomTabBarController 클래스의 changeIndex 속성을 구현하고 있습니다.
changeIndex는 Int 값을 받아와서 base.tabBar.rx.changeIndex.onNext(index)를 호출하는 Binder입니다. 이는 CustomTabBar 클래스의 rx.changeIndex Subject에 새로운 값을 전달하게 됩니다.
ReactiveX는 비동기적인 데이터 스트림을 다루기 위한 라이브러리이며, Binder는 그 중에서도 UI 컴포넌트와의 바인딩을 간단하게 구현하기 위한 것입니다. 따라서 이 코드는 CustomTabBarController의 changeIndex 속성을 통해 CustomTabBar의 rx.changeIndex Subject를 제어하고, 이를 통해 탭 바의 선택된 인덱스를 바꿀 수 있도록 도와주는 역할을 합니다.

2024-01-26 16:02 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/TabBar/TabBarController.swift
> +        setUp()
ViewDidLoad에서 호출하도록 했습니다.

2024-01-26 16:05 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/TabBar/TabBarController.swift
> +                guard let shouldFrontView = self.childVCs[index].view else { return }
[weak self]는 strong reference cycle을 방지하기 위한 것으로, 클로저 안에서 self를 참조할 때 주로 사용됩니다. 만약 self를 [weak self]로 선언하지 않으면 strong reference가 발생하여 메모리 누수의 위험이 있습니다. 혹시 self를 제거해서 어떤 식으로 코드를 써야할까요?

2024-01-26 16:08 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +        stackView.alignment = .center
// 스택 뷰를 lazy로 선언하여 클로저를 사용해 초기화
    private lazy var stackView: UIStackView = {
        let stackView = UIStackView()
        stackView.axis = .horizontal
        stackView.distribution = .fillEqually
        stackView.alignment = .center
        return stackView
    }() 로 변경했습니다.

2024-01-28 07:10 UTC, dami0806 commented on On_off_iOS/On_off_iOS/TabBar/CustomTabBar.swift
> +    fileprivate var selectedIndex = 0 {
fileprivate은 생략해도 default값이라 지워도 좋습니다!

2024-01-28 07:15 UTC, dami0806 commented on On_off_iOS/On_off_iOS/TabBar/TabBarController.swift
> +                guard let shouldFrontView = self.childVCs[index].view else { return }
아 아니요 guard let self를 사용해서 옵셔널 바인딩을 사용했기 때문에 그 밑줄의 self.childVCs에서의 self를 지워주세요

2024-01-28 07:22 UTC, HJ39 requested changes
다시 수정해주세요

2024-01-28 07:22 UTC, HJ39 commented on On_off_iOS/On_off_iOS/TabBar/View/TabBarController.swift
> +        tabBar.frame.size.height = UIScreen.main.bounds.height * 0.5
`UIScreen.main.bounds.height`
이거 deprecated 될 예정이라 `view.safeAreaLayoutGuide.layoutFrame.height` 이거로 수정해 주세요

2024-01-28 07:22 UTC, HJ39 commented on On_off_iOS/On_off_iOS/TabBar/View/TabBarController.swift
> +class TabBarController: UITabBarController {
앞에 final 붙여주세요

2024-01-28 07:22 UTC, HJ39 commented on On_off_iOS/On_off_iOS/TabBar/View/TabBarController.swift
> +        return UINavigationController(rootViewController: viewController)
SceneDelagete.swift 파일에서도 UINavigationController를 사용하고 있습니다.
둘중 하나를 지워주세요

2024-01-28 07:29 UTC, dami0806 commented on On_off_iOS/On_off_iOS/Extension/View/OnBoardingViewController.swift
우리아이 돌려주세요 Extension/View group에 있을 애가 아니에여ㅜㅜ

2024-01-29 07:07 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/TabBar/View/TabBarController.swift
> +        tabBar.frame.size.height = UIScreen.main.bounds.height * 0.5
넵!

2024-01-29 07:07 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/TabBar/View/TabBarController.swift
> +class TabBarController: UITabBarController {
넵!

2024-01-29 07:18 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/TabBar/View/TabBarController.swift
> +        return UINavigationController(rootViewController: viewController)
넵 return viewController로 변경했습니다.

2024-01-29 07:19 UTC, yeahzxnn commented on On_off_iOS/On_off_iOS/Extension/View/OnBoardingViewController.swift
안 건드렸는데ㅜ main에 어떻게 되어있는지 다시 확인해보고 되돌려놓을게요!

2024-01-29 08:52 UTC, HJ39 commented
위에 공간만 없애면 될거 같숨다ㅎ

2024-01-29 09:46 UTC, HJ39 approved these changes
👍

2024-01-30 05:06 UTC, merged